### ISSUE TITLE
New businessRule link broken?

### ISSUE THREAD

**Issue by tahartemin** [theotheu/dt#20]
Als ik op "New" (http://127.0.0.1:3000/#/businessrules/new) naast "businessRules" klik dan redirect de applicatie gelijk naar /#/books en laat een lijst van boeken zien.

Dit begon nadat ik een pull gedaan had om de veranderingen die gemerged zijn in development in mijn eigen branch te mergen.

Ik kan hier de oorzaak niet vinden. Iemand een idee welk obvious ding ik over het hoofd zie?

**Comment by tahartemin** [comment]
Nevermind, camel case issue in app.js. Routeprovider route stond op businessRules ipv businessrules.

**Comment by emielroelofsen** [comment]
Dat komt.omdat bij de route businessRule staat... de hoofdletter R
moet.een.kleine zijn
