### ISSUE TITLE
Create business rule model

### ISSUE THREAD

**Issue by tahartemin** [theotheu/dt#5]
Create model.
consists of:
-name
-model
-property (field)
-equation (use integer /list)
-expected value

create custom validators to check if model exists, grab that model and check if property exists for that model.

**Comment by mdondorp** [comment]
I've added an initial commit for these files, locally they allow for showing a page, will have to add proper page for this later today.

**Comment by tahartemin** [comment]
Do we put the checks for model and property existence in controller or model?

**Comment by theotheu** [comment]
Good question!

For this business rule app it should be in the controller.


Op dinsdag 26 mei 2015 heeft tahartemin <notifications@github.com> het
volgende geschreven:

> Do we put the checks for model and property existence in controller or
> model?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theotheu/dt/issues/5#issuecomment-105363242>.
>


-- 
With kind regards / met vriendelijke groet,

Theo Theunissen
06-28617829
