### ISSUE TITLE
working branch Michiel/Tim

### ISSUE THREAD

**Issue by tahartemin** [theotheu/dt#6]
Hi Michiel,

Wat is handig voor dit? Gaan we beiden een eigen implementatie uitvoeren op een local branch en overleggen we "offline" samen over wat de beste manier is om iets te implementeren? Werken we samen in een aparte combi branch voor ons beiden of wachten we totdat pull requests door Theo worden uitgevoerd zodat die onze local development branches updaten met elkaars code?

@theotheu hoe telt dit voor het commit bepaalt cijfer systeem aangezien wij beide aan hetzelfde werken in tegenstelling tot de rest?

**Comment by mdondorp** [comment]
Heb deze over het hoofd gezien, zal weer even een push doen, kon je misschien iets aan hebben.

**Comment by theotheu** [comment]
commits tellen -als baseline.
belangrijkste wat telt is wat je laat zien aan werkende code (1. t werkt) en dat het automatisch testbaar is en gedeployed kan worden (2. t werkt beter, het ++ deel)
